/*模拟数据*/
export default [{
    id: 1,
    img: '../../images/funa.png',
    name: '付娜1',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }, {
        text: '神经内科'
    }, {
        text: '主任医师'
    }, {
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜2',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜3',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜4',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜5',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜6',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}, {
    id: 1,
    img: '../../images/funa.png',
    name: '付娜7',
    title: '会计法上地嘉禾奥斯卡剪短发',
    desc: '爱上的回复过我尔雅交电话费噶但是安静的双方各安静的华国锋安吉大道附近拉带回来氨基酸的符合阿世纪东方',
    props: [{
        text: '神经内科'
    }, {
        text: '主任医师'
    }],
    comment: 11,
    thumb: 11,
    time: 10,
    comment: 11,
    thumb: 11,
    time: 10
}]